In [1]:
import os
os.chdir(r'D:\JenuChacko\20180511_\FLIM_CALIBRATION\mink_pyc')
import spc_asc as sa
import sdt_tools as sd
import gui_tools as gt
import seaborn as sns
import pandas as pd
import glob
get_rep=sd.get_rep

In [2]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


## CHECKING OLDER DATA  OCT 23,2017

In [123]:
f1=r'L:\ORGANIZED_DATA\CONFLUENCY\20171013_confluency\10A\analysis\img'
df.to_csv('data_reanalyzed.csv')

In [121]:
#dfa=df.copy()
print df.well.unique()
#for i in dfa.well.unique(): 
W=[]
for i in df.well: 
    if i==20:
        Well='L'
    else:
        if i==40:
            Well='K'
        else:
            if i==80:
                Well='J'
            else:
                if i==120:
                    Well='I'
                else:
                    if i==160:
                        Well='H'
                    else:
                        if i==200:
                            Well='G'
                        else:    
                            if i==400:
                                Well='F'
                            else:
                                if i==800:
                                    Well='E'
                                else:
                                    if i==1200:
                                        Well='D'
                                    else:
                                        if i==1600:
                                            Well='C'
                                        else:
                                            if i==2000:
                                                Well='B'
                                            else:    
                                                if i==2400:
                                                    Well='A'
                                                else:
                                                    print i
    W.append(Well)
df['Well']=W
print df.Well.unique()

[  20   40   80  120  160  200  400  800 1200 1600 2000 2400]
['L' 'K' 'J' 'I' 'H' 'G' 'F' 'E' 'D' 'C' 'B' 'A']


In [122]:
df.shape

(71975, 20)

# COMPILING - MAY11-MAY 15, 2018

In [3]:
# FILE TIMES
import os

In [5]:
def get_sdt_creation(folder1,printon=True):
    import os
    os.chdir(folder1)
    fl=glob.glob('*.sdt')
    import os.path, time
    for file1 in fl:
        if printon:
            print("last modified: %s" % time.ctime(os.path.getmtime(file1)))
            #print("created: %s" % time.ctime(os.path.getctime(file1)))
    return(os.path.getmtime(file1))

print get_sdt_creation(r'D:\JenuChacko\20180513_conf\CONF_8\10A')


#a= os.path.getmtime(file1)
#b= time.time()
#print (b-a),'sec'
#print (b-a)/60,'min',(b-a)/(60*60),'hrs' ,(b-a)/(60*60*24),'days'
def print_realtime(epotime,printon=True):
    s=round(epotime)
    m=round(s/60,2)
    h=round(m/60,2)
    d=round(h/24,2)
    if printon:
        print (s),'sec'
        print m,'min',h,'hrs',d,'days'
    return([d,h,m,s])
#print_realtime(b-a)



last modified: Sun May 13 16:26:13 2018
last modified: Sun May 13 16:27:47 2018
last modified: Sun May 13 16:29:21 2018
last modified: Sun May 13 16:17:58 2018
last modified: Sun May 13 16:19:31 2018
last modified: Sun May 13 16:21:05 2018
last modified: Sun May 13 16:10:39 2018
last modified: Sun May 13 16:12:14 2018
1526245934.33


### GET TIME FROM SDT or BRT FLD

In [210]:
# PLATING TIME
file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\10a_count\10a_count_MMStack_Pos0.ome.tif'
print(time.ctime(os.path.getmtime(file1)))
plating_time=os.path.getmtime(file1)

print 

file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\d24_10a_8well\d24_10a_8well_MMStack_Pos0.ome.tif'
brightfield_time1=os.path.getmtime(file1)
print 'BF_1:',
print(time.ctime(brightfield_time1)),print_realtime(brightfield_time1-plating_time,False)


file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\d36_10A_8well\d36_10a_8well_MMStack_Pos0.ome.tif'
brightfield_time2=os.path.getmtime(file1)
print 'BF_2:',
print(time.ctime(brightfield_time2)),print_realtime(brightfield_time2-plating_time,False)

file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\d96_10A_8well\d96_10a-8_MMStack_Pos0.ome.tif'
brightfield_time3=os.path.getmtime(file1)
print 'BF_3:',
print(time.ctime(brightfield_time3)),print_realtime(brightfield_time3-plating_time,False)

print

file1=r'D:\JenuChacko\20180513_conf\CONF_8\10A'
flim1=get_sdt_creation(file1,printon=False)
print 'FLIM1:',
print time.ctime(flim1),print_realtime(flim1-plating_time,False)

file1=r'D:\JenuChacko\20180514\8_WELL\10A'
flim2=get_sdt_creation(file1,printon=False)
print 'FLIM2:',
print time.ctime(flim2),print_realtime(flim2-plating_time,False)

file1=r'D:\JenuChacko\20180517\10A_8well'
flim3=get_sdt_creation(file1,printon=False)
print 'FLIM3:',
print time.ctime(flim3),print_realtime(flim3-plating_time,False)


Fri May 11 18:16:09 2018

BF_1: Sat May 12 20:39:30 2018 [1.1, 26.39, 1583.37, 95002.0]
BF_2: Sun May 13 13:48:31 2018 [1.81, 43.54, 2612.37, 156742.0]
BF_3: Tue May 15 12:43:59 2018 [3.77, 90.46, 5427.83, 325670.0]

FLIM1: Sun May 13 16:12:14 2018 [1.91, 45.93, 2756.08, 165365.0]
FLIM2: Tue May 15 01:00:56 2018 [3.28, 78.75, 4724.78, 283487.0]
FLIM3: Thu May 17 14:20:34 2018 [5.84, 140.07, 8404.42, 504265.0]


In [222]:
file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\10a_count\10a_count_MMStack_Pos0.ome.tif'
print(time.ctime(os.path.getmtime(file1)))
plating_time=os.path.getmtime(file1)


file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\P2\D170_10A_8well\D170_10a_8_MMStack_Pos0.ome.tif'
brightfield_time4=os.path.getmtime(file1)
print 'BF_4:',
print(time.ctime(brightfield_time4)),print_realtime(brightfield_time4-plating_time,False)


file1=r'D:\JenuChacko\20180511_\BRIGHTFIELD\P2\D240_10A_8well\D_LAST-10-8_MMStack_Pos0.ome.tif'
brightfield_time5=os.path.getmtime(file1)
print 'BF_5:',
print(time.ctime(brightfield_time5)),print_realtime(brightfield_time5-plating_time,False)



Fri May 11 18:16:09 2018
BF_4: Thu May 17 19:20:39 2018 [6.04, 145.07, 8704.5, 522270.0]
BF_5: Sun May 20 23:06:43 2018 [9.2, 220.84, 13250.57, 795034.0]


### COMPILE SDT INTO XLS FROM 3 DAYS

In [498]:
os.chdir(r'D:\JenuChacko\20180513_conf')
dfa=pd.read_csv(r'results_12W.csv')
dfa['well_size']='12x'
dfb=pd.read_csv(r'results_8W.csv')
dfb['well_size']='8x'
dfD1=dfa.append(dfb)
dfD1['time']=45.93
dfD1['Day']=2

os.chdir(r'D:\JenuChacko\20180514')
dfa=pd.read_csv(r'results_12W_90.csv')
dfa['well_size']='12x'
dfb=pd.read_csv(r'results_8W_90.csv')
dfb['well_size']='8x'
dfD2=dfa.append(dfb)
dfD2['time']=78.75
dfD2['Day']=3

os.chdir(r'D:\JenuChacko\20180517_conf\12_well')
dfa=pd.read_csv(r'results_12W_10A.csv')
dfa=dfa.append(pd.read_csv(r'results_12W_231.csv'))
dfa=dfa.append(pd.read_csv(r'results_12W_10A_p2.csv'))
dfa=dfa.append(pd.read_csv(r'results_12W_231_p2.csv'))


dfa['well_size']='12x'
os.chdir(r'D:\JenuChacko\20180517_conf\8_well')
dfb=pd.read_csv(r'results_8W_10A.csv')
dfb=dfb.append(pd.read_csv(r'results_8W_231.csv'))
dfb['well_size']='8x'
dfD3=dfa.append(dfb)
dfD3['time']=140.07
dfD3['Day']=4

c=[]
for i in dfD3.cell:
    if i==231:
        c.append('231')
    else:
        c.append(i)
dfD3['cell']=c

print dfD1.shape,dfD2.shape,dfD3.shape
print dfD1.well.unique()
print dfD2.well.unique()
print dfD3.well.unique()
print dfD1.cell.unique(),dfD2.cell.unique(),dfD3.cell.unique()

df=dfD1.append(dfD2)
df=df.append(dfD3)


(4000, 22) (8353, 24) (24190, 22)
['A' 'B' 'C' 'F']
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'j' 'K' 'L' 'J']
['G' 'H' 'I' 'J' 'K' 'L' 'A' 'B' 'C' 'D' 'E' 'F']
['10A' '231'] ['10A' '231'] ['10A' '231']


In [499]:
df.columns

Index([u'Day', u'Intensity', u'Unnamed: 0', u'Unnamed: 0.1', u'a1', u'a1p',
       u'a1w', u'a2', u'a2p', u'cell', u'chi', u'fid', u'g', u'i', u'itm',
       u'mask_size', u'phase', u's', u't1', u't2', u'time', u'tm', u'well',
       u'well_size'],
      dtype='object')

In [500]:
del df[u'Unnamed: 0']
del df[u'Unnamed: 0.1']
df.columns

Index([u'Day', u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p', u'cell',
       u'chi', u'fid', u'g', u'i', u'itm', u'mask_size', u'phase', u's', u't1',
       u't2', u'time', u'tm', u'well', u'well_size'],
      dtype='object')

In [503]:
os.chdir(r'D:\JenuChacko\20180517_conf')
df.to_csv('data.csv')

# COMMON

In [501]:
df=df.replace('j','J')

In [502]:
print df.well.unique()
print df.cell.unique()
print df.well_size.unique()
print df.time.unique()
print df.Day.unique()

['A' 'B' 'C' 'F' 'D' 'E' 'G' 'H' 'I' 'J' 'K' 'L']
['10A' '231']
['12x' '8x']
[  45.93   78.75  140.07]
[2 3 4]


In [305]:
c=[]
for i in df1.cell:
    if i==231:
        c.append('231')
    else:
        c.append(i)
df1['cell']=c
df1.cell.unique()

array(['10A', '231'], dtype=object)

In [ ]:
df['time']=0
df['sp']=0
df['cell']='10A'
df['RT']=df.time*1.5

In [309]:
print df1.cell.unique()
#df1=df1.replace('a','A')
#df1=df1.replace('F2','F')

['10A' '231']


In [310]:
TP=[]
SP=[]
cell=[]
for i in df.fid:
    j=i.split('_')
    TP.append(j[-4][2:])
    SP.append(j[-3][2:])
    cell.append(j[5])
df['time']=TP
df['sp']=SP
df['cell']=cell

df['time'] = pd.to_numeric(df['time'], errors='coerce')
df.time.unique()

df['RT']=df.time*1.5

df.RT.unique(),df.cell.unique()


In [387]:
#df.to_csv(r'D:\JenuChacko\20180511_\FLIM_CALIBRATION\mink_pyc\data_20171013.csv')

# MAKING CSV

In [561]:
#f1=r'D:\JenuChacko\20180514\10a_celltime\C6'
#f1=r'D:\JenuChacko\20180514\8_WELL\231'
#f1=r'D:\JenuChacko\20180513_conf\CONF_8\231'
#f1=r'D:\JenuChacko\20180514\12well\231'
#f1=r'D:\JenuChacko\20180517_conf\12_well\10A_12well\part2'
#f1=r'L:\ORGANIZED_DATA\CONFLUENCY\20171013_confluency\PANC\analysis\img'
f1=r'D:\JenuChacko\20180520_\12Well_10A\img'



os.chdir(f1)
asc_objs=[]
fl=glob.glob('*photons.asc')

for ix,i in enumerate(fl):
    asc_objs.append(sa.spc_ascii(i))
    print ix*100//len(fl),
    
for ix,i in enumerate(asc_objs):
    dfa=i.generate_df()
    if ix==0:
        df=dfa
    else:
        df=df.append(dfa)
print df.shape

0 4 8 12 16 20 25 29 33 37 41 45 50 54 58 62 66 70 75 79 83 87 91 95 (12148, 16)


In [556]:
#df10a=df.copy()
#dfca1d=df.copy()
#dfhpv=df.copy()
#dfpanc=df.copy()
#print df10a.shape,dfca1d.shape,dfhpv.shape,dfpanc.shape

#df=df10a.append(dfca1d)
#df=df.append(dfhpv)
#df=df.append(dfpanc)

#print df.shape

In [557]:
for i in df.fid.unique():
    print i.split('_')
    #well= int(i.split('_')[1][:-1])
    #print well

['231', 'well', 'A', '1', 'photons.asc']
['231', 'well', 'A', '2', 'photons.asc']
['231', 'well', 'B', '1', 'photons.asc']
['231', 'well', 'B', '2', 'photons.asc']
['231', 'well', 'C', '1', 'photons.asc']
['231', 'well', 'C', '2', 'photons.asc']
['231', 'well', 'D', '1', 'photons.asc']
['231', 'well', 'D', '2', 'photons.asc']
['231', 'well', 'E', '1', 'photons.asc']
['231', 'well', 'E', '2', 'photons.asc']
['231', 'well', 'F', '1', 'photons.asc']
['231', 'well', 'F', '2', 'photons.asc']
['231', 'well', 'F', '3', 'photons.asc']
['231', 'well', 'G', '1', 'photons.asc']
['231', 'well', 'G', '2', 'photons.asc']
['231', 'well', 'H', '1', 'photons.asc']
['231', 'well', 'H', '2', 'photons.asc']
['231', 'well', 'I', '1', 'photons.asc']
['231', 'well', 'I', '2', 'photons.asc']
['231', 'well', 'J', '1', 'photons.asc']
['231', 'well', 'J', '2', 'photons.asc']
['231', 'well', 'K', '1', 'photons.asc']
['231', 'well', 'K', '2', 'photons.asc']
['231', 'well', 'L', '1', 'photons.asc']
['231', 'well', 

In [562]:
w=[]
c=[]
for i in df.fid:
    #w.append(int(i.split('_')[1][:-1]))
    w.append(i.split('_')[2])
    c.append(i.split('_')[0])
print w[0],c[0]
df['cell']=c
df['well']=w

A 10A


In [563]:
df['i']=df['Intensity']/df['mask_size']

In [564]:
os.chdir(r'D:\JenuChacko\20180520_')
df.to_csv('results_10A_12well.csv')

In [565]:
os.getcwd()

'D:\\JenuChacko\\20180520_'

## MAY 14


In [496]:
#os.chdir(r'D:\JenuChacko\20180514\8_WELL')
#df1=pd.read_csv('results_10A.csv')
#df2=pd.read_csv('results_231.csv')
#df=df1.append(df2)

os.chdir(r'D:\JenuChacko\20180514\12well')
df1=pd.read_csv('results_10A_1.csv')
df2=pd.read_csv('results_10A_2.csv')
df3=pd.read_csv('results_231_1.csv')
df4=pd.read_csv('results_231_2.csv')
df=df1.append(df2.append(df3.append(df4)))
df.head()
df=df.replace('10a','10A')
df.shape

(6095, 20)

In [497]:
os.chdir(r'D:\JenuChacko\20180514')
df.to_csv(r'results_12W_90.csv')

## CELL TIME

In [566]:
os.chdir(r'D:\JenuChacko\20180514\10a_celltime')
df0=pd.read_csv('results_C0.csv')
df1=pd.read_csv('results_C1.csv')
df3=pd.read_csv('results_C3.csv')
df4=pd.read_csv('results_C4.csv')
df5=pd.read_csv('results_C5.csv')

In [ ]:
#### 10A cells
#C0 1 x2 files in 11.14 - 11:12 =     0
#             -- 7 min
#C1  5x2+1 files in 11:37 - 11:21 =   0.16 
#            -- 2 min
# C3 100x2 in  4:55PM-11.39AM    =    5: 16
#               -- 11 min 
#C4 :               5:06            0
#                 -- 3 min
# C05 : 100x2 - 10:22PM- 5:09PM =     5: 13
#                 11 min
#C06 : 10:33

In [567]:
print 5*60 + 16, 316.0/100
print 5*60 + 13, 313.0/100

316 3.16
313 3.13


In [568]:
df0.RT=df0.time*3.13 #C0
df1.RT=df0.RT.max()+ 7+(df1.time*3.13) #C1
df3.RT=df1.RT.max()+2+ (df3.time*3.13) #C3
df4.RT=df3.RT.max()+11+ (df4.time*3.13) #C4
df5.RT=df4.RT.max()+3+ (df5.time*3.13) #C5

In [569]:
df=df0.append(df1.append(df3.append(df4.append(df5))))

In [570]:
plot(df.RT.values)

In [571]:
os.chdir(r'D:\JenuChacko\20180511_\FLIM_CALIBRATION\cell_time')
dfc=pd.read_csv('results_C.csv')
dfd=pd.read_csv('results_D.csv')
dfe=pd.read_csv('results_E.csv')

In [572]:
dfd.RT.unique()

array([   0. ,    3. ,    4.5,    6. ,    7.5,    9. ,   10.5,   12. ,
         13.5,   15. ,   16.5,   18. ,   19.5,   21. ,   22.5,   24. ,
         25.5,   27. ,   28.5,    1.5,   30. ,   31.5,   33. ,   34.5,
         36. ,   37.5,   39. ,   40.5,   42. ,   43.5,   45. ,   46.5,
         48. ,   49.5,   51. ,   52.5,   54. ,   55.5,   57. ,   58.5,
         60. ,   61.5,   63. ,   64.5,   66. ,   67.5,   69. ,   70.5,
         72. ,   73.5,   75. ,   76.5,   78. ,   79.5,   81. ,   82.5,
         84. ,   85.5,   87. ,   88.5,   90. ,   91.5,   93. ,   94.5,
         96. ,   97.5,   99. ,  100.5,  102. ,  103.5,  105. ,  106.5,
        108. ,  109.5,  111. ,  112.5,  114. ,  115.5,  117. ,  118.5,
        120. ,  121.5,  123. ,  124.5,  126. ,  127.5,  129. ,  130.5,
        132. ,  133.5,  135. ,  136.5,  138. ,  139.5,  141. ,  142.5,
        144. ,  145.5,  147. ,  148.5])

In [573]:
#### 231 cells

#C  45 files in 1:51 - 11:36  = 2:15
#  -- 6 min
#D 100 x2 files in 1:57 - 7:10 = 5;13
# -- 3:08
#E  60 files in 11:29 - 10:18 = 1:11

In [574]:
print 2*60 + 15, 135.0/45
print 5*60 + 13, 313.0/100
print 1*60 + 11, 71.0/60

135 3.0
313 3.13
71 1.18333333333


In [575]:
dfd.time.unique()

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19,  1, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64)

In [576]:
dfc.RT.max()

66.0

In [577]:
dfc.RT=dfc.time*3.0
dfd.RT=dfc.RT.max()+ 6+(dfd.time*3.13)
dfe.RT=dfd.RT.max()+188+ (dfe.time*1.18)

In [578]:
df=dfc.append(dfd)
df=df.append(dfe)

In [579]:
df['rt']=df['RT']/60.0

# PLOTTING

In [59]:
df.columns

Index([u'Unnamed: 0', u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p',
       u'chi', u'fid', u'g', u'itm', u'mask_size', u'phase', u's', u't1',
       u't2', u'tm', u'time', u'sp', u'cell', u'RT', u'rt'],
      dtype='object')

In [60]:
df=df.loc[df.sp==0]

In [71]:
df.sp.unique()

array([0], dtype=int64)

In [62]:
df.columns

Index([u'Unnamed: 0', u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p',
       u'chi', u'fid', u'g', u'itm', u'mask_size', u'phase', u's', u't1',
       u't2', u'tm', u'time', u'sp', u'cell', u'RT', u'rt'],
      dtype='object')

In [80]:
df.head()

Unnamed: 0  Unnamed: 0.1  Intensity            a1       a1p       a1w  \
0           0             0       26.0  1.000000e-08  0.012818  0.000657   
1           1             1       26.0  1.000000e-08  0.014489  0.000921   
2           2             2       26.0  1.000000e-08  0.015527  0.001219   
3           3             3       26.0  1.000000e-08  0.016312  0.001503   
4           4             4       26.0  1.000000e-08  0.017291  0.001928   

             a2       a2p       chi  \
0  1.000000e-08  0.013835  0.757027   
1  1.000000e-08  0.015594  0.787779   
2  1.000000e-08  0.016821  0.802499   
3  1.000000e-08  0.017821  0.816450   
4  1.000000e-08  0.018850  0.827159   

                                                 fid ...      phase         s  \
0  C1_230PC_18khz_90sec_45070nm_10A_20LX075NA_TP0... ...   1.001062  0.042609   
1  C1_230PC_18khz_90sec_45070nm_10A_20LX075NA_TP0... ...   1.003395  0.143934   
2  C1_230PC_18khz_90sec_45070nm_10A_20LX075NA_TP0... ...   1.005646  0.186424   
3  C1_230PC_18khz_90sec_45070nm_10A_20LX075NA_TP0... ...   1.008504  0.203551   
4  C1_230PC_18khz_90sec_45070nm_10A_20LX075NA_TP0... ...   1.011177  0.211051   

         t1        t2         tm  time  sp  cell   RT   rt  
0  20.05475  349.5680   86.19385     0   0   10A  0.0  0.0  
1  20.84880  459.4565  315.83000     0   0   10A  0.0  0.0  
2  22.06680  494.6025  403.30900     0   0   10A  0.0  0.0  
3  24.24980  520.3915  433.18350     0   0   10A  0.0  0.0  
4  27.48730  537.5440  454.32000     0   0   10A  0.0  0.0  

[5 rows x 23 columns]

In [580]:
dfa=df.groupby(['RT','cell']).median()
dfa=dfa.reset_index()
#dfa
dfa.head()

RT  cell  Unnamed: 0  Intensity        a1        a1p        a1w  \
0   0.0   231       124.0       35.0  0.000121  81.514450  50.687055   
1   3.0   231       124.0       36.0  0.000129  81.557150  48.393663   
2   6.0   231       123.5       36.5  0.000129  81.520650  48.199511   
3   9.0   231       125.0       37.0  0.000132  81.558150  47.521233   
4  12.0   231       125.5       36.0  0.000133  81.852275  48.813666   

         a2        a2p       chi  ...           itm  mask_size     phase  \
0  0.000035  18.456600  1.014035  ...   1360.943358    12478.0  3.636730   
1  0.000039  18.441550  1.018680  ...   1370.387613    12453.0  3.762666   
2  0.000039  18.453675  1.025562  ...   1374.422147    12431.0  3.750400   
3  0.000041  18.402700  1.015230  ...   1359.162189    12597.0  3.835888   
4  0.000040  18.125425  1.024317  ...   1338.320865    12626.0  3.780006   

          s         t1        t2         tm  time   sp    rt  
0  0.331336  640.11350  2126.715  922.16100   0.0  0.0  0.00  
1  0.322794  600.41350  2159.580  918.24150   1.0  0.0  0.05  
2  0.323011  606.28525  2152.290  913.39750   2.0  0.0  0.10  
3  0.312314  554.61800  2120.280  895.97050   3.0  0.0  0.15  
4  0.315434  577.94450  2118.680  901.13325   4.0  0.0  0.20  

[5 rows x 21 columns]

In [582]:
sns.lmplot('rt','Intensity',hue='cell',data=dfa)
sns.lmplot('rt','tm',hue='cell',data=dfa)

In [86]:
sns.regplot('RT','t2',data=dfa)
sns.regplot('RT','t1',data=dfa)

In [87]:
dfa.columns

Index([u'RT', u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p', u'chi', u'g',
       u'itm', u'mask_size', u'phase', u's', u't1', u't2', u'tm', u'time'],
      dtype='object')

In [87]:
#sns.regplot('RT','phase',data=dfa)
sns.regplot('RT','itm',data=dfa)

In [88]:
sns.countplot(x='mask_size',data=dfa,palette='Greens_d')

In [89]:
sns.lmplot('g','s',hue='time',data=dfa,fit_reg=False,palette='RdBu')
gt.plot_univ_circle_v1()

In [90]:
dfa.shape

(412, 22)

In [91]:
sns.pointplot('rt','tm',data=df.loc[df.rt<5],palette='RdBu',capsize=.2)

In [66]:
os.chdir(r'D:\JenuChacko\20180511_\FLIM_CALIBRATION\mink_pyc')

In [67]:
df=pd.read_csv('10Acells.csv')
df=df.append(pd.read_csv('231cells.csv'))
df.shape

(142836, 23)

In [112]:
sns.barplot('cell','a2',data=dfa)

In [116]:
sns.lmplot('g','s',hue='cell',data=dfa,palette='RdBu',fit_reg=False)
#gt.plot_univ_circle_v1()
axis([0,1,0,1])

[0, 1, 0, 1]

In [131]:
sns.lmplot('RT','phase',hue='cell',hue_order=['231','10A'],data=dfa,
           palette='Set1',fit_reg=False)


In [129]:
for i in df.columns:
    print i


Unnamed: 0
Unnamed: 0.1
Intensity
a1
a1p
a1w
a2
a2p
chi
fid
g
itm
mask_size
phase
s
t1
t2
tm
time
sp
cell
RT
rt


In [100]:
dfa=df.groupby(['well','cell']).mean()
dfa.reset_index(inplace=True)

In [85]:
sns.lmplot('g','s',hue='cell',col='well',data=dfa,fit_reg=False,palette='RdBu')
gt.plot_univ_circle_v1()

In [101]:
sns.boxplot('well','tm',hue='cell',data=df,palette='muted')

In [82]:
sns.barplot('well','a1w',hue='cell',data=dfa,palette='Set1')

In [287]:
df.columns

Index([u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p', u'cell', u'chi',
       u'fid', u'g', u'itm', u'mask_size', u'phase', u's', u't1', u't2',
       u'time', u'tm', u'well', u'well_size'],
      dtype='object')

## PLOT for  LARGE "data.csv"

In [504]:
df['i']=df['Intensity']/df['mask_size']

In [508]:
dfa=df.groupby(['well','cell','well_size','time','Day']).mean()
dfa.reset_index(inplace=True)

In [509]:
dfa.shape

(90, 21)

In [353]:
#sns.barplot('well','a1w',hue='cell',data=dfa,palette='Set1')

In [510]:
dfa.well_size.unique()

array(['12x', '8x'], dtype=object)

In [511]:
sns.lmplot('g','s',hue='well',
           row='cell',col='time',
           data=dfa.loc[(dfa.well_size=='12x')],
           palette='RdBu',fit_reg=False)
#gt.plot_univ_circle_v1()

In [538]:
#matplotlib.style.use('ggplot')
matplotlib.style.use('bmh')


In [384]:
#dfa.loc[dfa.cell=='231']

In [441]:
sns.lmplot('a1p','tm',hue='well',
           row='cell',col='time',
           data=dfa.loc[(dfa.well_size=='12x')&(dfa.a1p>0)],
           palette='PuBuGn_d',fit_reg=False)

In [442]:
df.time.unique()

array([  45.93,   78.75,  140.07])

In [449]:
figure()
dfs=df.loc[(df.well_size=='8x')&(df.Day==4)]
print dfs.shape
order_2plot=list(dfs.well.unique())
order_2plot.sort()
sns.pointplot(x='well',y='tm',data=dfs,hue='cell',
            order=order_2plot,            
            palette='muted')

(9748, 24)


In [512]:
g = sns.factorplot(x="well", y="tm",
                   hue="cell", col="well_size",row='time',
                   data=df,
                   kind="strip",jitter=.3,split=True,marker='.')

In [455]:
g = sns.factorplot(x="well", y="tm",
                   hue="cell",hue_order=['231','10A'],col="well_size",row='time',
                   data=df,palette='Set1',
                   kind="violin",split=True,marker='.')

In [513]:
df.shape,dfa.shape

((36543, 22), (90, 21))

In [83]:
dfa=df.groupby(['well','cell','fid']).mean()
dfa.reset_index(inplace=True)

[  20   40   80  120  160  200  400  800 1200 1600 2000 2400]
['L' 'K' 'J' 'I' 'H' 'G' 'F' 'E' 'D' 'C' 'B' 'A']


In [28]:
g = sns.factorplot(x="well", y="tm",
                   hue="cell",
                   data=dfa,palette='Set1',
                   kind="point",jitter=.3,split=True,marker='.')

In [514]:
os.chdir(r'D:\JenuChacko\20180517_conf')
df_18may=pd.read_csv('data.csv')

In [515]:
dfB=df_18may.loc[df_18may.well_size=='12x']
dfb=dfB.groupby(['well','cell','fid','time']).mean()
dfb.reset_index(inplace=True)

In [516]:
dfB.shape,dfb.shape,dfa.shape

((23218, 23), (85, 22), (90, 21))

In [517]:
g = sns.factorplot(x="well", y="tm",
                   hue="cell",row='time',
                   data=dfB,palette='Set1',
                   kind="point",jitter=.3,split=True,marker='.')

order_2plot=list(dfa.Well.unique())
order_2plot.sort()

g = sns.factorplot(x="Well", y="tm",
                   hue="cell",
                   order=order_2plot,
                   data=dfa,palette='Set1',
                   kind="point",jitter=.3,split=True,marker='.')

AttributeError: 'DataFrame' object has no attribute 'Well'

In [58]:
#dfa2 = dfa.sort_index(dfa['Well']).reset_index()

In [139]:
dfa=df.groupby(['Well','cell','fid']).mean()
dfa.reset_index(inplace=True)

In [140]:
order_2plot=list(dfa.Well.unique())
order_2plot.sort()

g = sns.factorplot(x="Well", y="g",
                   hue="cell",
                   order=order_2plot,
                   data=dfa,palette='Set1',
                   kind="point",jitter=.3,split=True,marker='.')

In [142]:
sns.lmplot('a1p','tm',hue='Well',
           col='cell',
           data=dfa,
           palette='PuBuGn_d',fit_reg=False)

In [147]:
dfa=df.groupby(['Well','cell']).mean()
dfa.reset_index(inplace=True)
dfa.shape

(48, 19)

In [458]:
os.chdir(r'L:\ORGANIZED_DATA\CONFLUENCY\20171013_confluency')
dfaa=pd.read_excel('20171027_output.xlsx')
dfaa.shape

(48, 4)

In [459]:
dfa.head()

well cell well_size    time  Day   Intensity  Unnamed: 0  Unnamed: 0.1  \
0    A  10A       12x   45.93  2.0  234.641748  257.000000           NaN   
1    A  10A       12x   78.75  3.0  235.385496  261.500000         261.5   
2    A  10A       12x  140.07  4.0  223.515964  195.687101           NaN   
3    A  10A        8x   45.93  2.0   42.090183   81.002283           NaN   
4    A  10A        8x   78.75  3.0   55.518581  147.500000         147.5   

         a1        a1p     ...            chi         g         i  \
0  0.000602  73.379303     ...       1.054992  0.721967  0.009106   
1  0.000301  75.692346     ...       1.004442  0.789790  0.008975   
2  0.000284  74.599270     ...       0.990939  0.786482  0.011406   
3  0.000100  71.134897     ...       1.008940  0.765043  0.006110   
4  0.000041  63.378021     ...       1.095978  0.812529  0.003748   

           itm     mask_size     phase         s          t1           t2  \
0  2884.818862  25769.000000  6.378923  0.317635  630.655600  3919.929039   
1  2243.727609  26227.000000  6.667814  0.284257  489.645086  3138.115296   
2  2259.377670  19632.280971  7.454756  0.276626  470.854711  3072.850390   
3  2421.085877   8179.196347  5.747241  0.316864  647.034153  3261.881226   
4  1281.843372  14811.000000  3.292023  0.346463  693.913302  1817.248919   

            tm  
0  1495.033846  
1  1112.269512  
2  1117.295966  
3  1345.669199  
4   999.433319  

[5 rows x 23 columns]

In [173]:
dfaa=dfaa.sort_values(by=['well','cell'])
dfaa.reset_index(inplace=True)
#del dfaa['level_0']
#del dfaa['index']

In [174]:
dfaa.head()

cell well      mean       std
0   10A    A  0.859091  0.153686
1  CA1D    A  0.302556  0.054412
2   HPV    A  0.958400  0.080074
3  PANC    A  0.893800  0.063674
4   10A    B  0.905643  0.090807

In [202]:
dfa['conf']=dfaa['mean']*100
dfa['conf']=dfa['conf'].astype(int)
dfa['conf_std']=dfaa['std']*100
dfa['conf_std']=dfa['conf_std'].astype(int)

In [216]:
sns.lmplot('conf','tm',hue='Well',
           col='cell',
           data=dfa,
           palette=sns.dark_palette("purple"),fit_reg=False)

In [219]:
dfa['conf']=dfaa['mean']*4
dfa['conf']=dfa['conf'].astype(int)
dfa['conf']=dfa['conf']*25

g = sns.factorplot(x="conf", y="tm",
                   hue='cell',
                   data=dfa,
                   kind="point")

In [201]:
sns.boxplot(x='cell',y='tm',data=dfa)

In [209]:
dfa.to_excel('20180520_sorted_out.xls')

In [518]:
os.chdir(r'D:\JenuChacko\20180517_conf')
df_18may=pd.read_csv('data.csv')

In [519]:
df_18may.time.unique(),df_18may.Day.unique(),df_18may.well.unique()


(array([  45.93,   78.75,  140.07]),
 array([2, 3, 4], dtype=int64),
 array(['A', 'B', 'C', 'F', 'D', 'E', 'G', 'H', 'I', 'J', 'K', 'L'], dtype=object))

In [520]:
dfB=df_18may.loc[(df_18may.well_size=='12x')&(df_18may.Day!=2)]
dfb=dfB.groupby(['well','cell','Day','well_size']).mean()
dfb.reset_index(inplace=True)

In [521]:
dfb.shape

(48, 22)

In [522]:
os.chdir(r'D:\JenuChacko\20180511_\BRIGHTFIELD')
dfbb=pd.read_excel('data_output.xlsx')

In [523]:
dfbb.columns

Index([u'time', u'well', u'cell', u'wellsize', u'mean'], dtype='object')

In [524]:
dfbb.time.unique()

array([u'D1', u'D2', u'D3', u'D4', u'D5', u'D4_wash'], dtype=object)

In [525]:
c=[]
for i in dfbb.cell:
    if i==231:
        c.append('231')
    else:
        c.append(i)
dfbb['cell']=c

dfbb.cell.unique()

array([u'10A', '231'], dtype=object)

In [529]:
dfbb['conf']=dfbb['mean']*100
dfbb['conf']=dfbb['conf'].astype(int)
#dfbb['conf']=dfbb['conf']*25

g = sns.factorplot(x="well", y="conf",
                   hue='cell',col='wellsize',
                   row='time',
                   data=dfbb,
                   kind="point")

In [255]:
# PBS WASH on 12 WELL

sns.factorplot(x="well", y="conf",
                   hue='cell',col='time',
                   data=dfbb.loc[(dfbb.wellsize=='12x')&((dfbb.time=='D4_wash')|(dfbb.time=='D4'))],
                   kind="point")

In [272]:
dfbb2=dfbb.loc[((dfbb.time=='D3')|(dfbb.time=='D4'))&(dfbb.wellsize=='12x')]
dfbb2.reset_index(inplace=True)
dfbb2=dfbb2.rename(columns={'time': 'Day'})

In [412]:
dfb.head()

well cell  Day well_size  Unnamed: 0   Intensity  Unnamed: 0.1  \
0    A  10A    3       12x       261.5  235.385496    261.500000   
1    A  10A    4       12x       391.0  223.515964    195.687101   
2    A  231    3       12x      4195.5  280.236650    205.500000   
3    A  231    4       12x       476.5  251.778302    238.004193   
4    B  10A    3       12x       817.0  270.627768    817.000000   

   Unnamed: 0.1.1        a1        a1p     ...              g         i  \
0           261.5  0.000301  75.692346     ...       0.789790       NaN   
1             NaN  0.000284  74.599270     ...       0.786482       NaN   
2           205.5  0.000439  77.695104     ...       0.816208  0.013572   
3             NaN  0.000552  81.565793     ...       0.882272       NaN   
4           293.0  0.000364  76.026407     ...       0.792500       NaN   

           itm     mask_size     phase         s          t1           t2  \
0  2243.727609  26227.000000  6.667814  0.284257  489.645086  3138.115296   
1  2259.377670  19632.280971  7.454756  0.276626  470.854711  3072.850390   
2  1839.307484  20648.000000  5.994659  0.279761  473.772624  2714.994539   
3  1300.799741  23863.436059  6.417800  0.224885  344.310500  2017.374654   
4  2121.717434  29397.000000  6.207507  0.289280  499.238681  3018.218135   

     time           tm  
0   78.75  1112.269512  
1  140.07  1117.295966  
2   78.75   955.436525  
3  140.07   650.271372  
4   78.75  1083.279465  

[5 rows x 24 columns]

In [293]:
del[dfbb2['index']]

In [294]:
dfbb2.sort_values(by=['well','cell','Day','wellsize'],inplace=True)
dfbb2.reset_index(inplace=True)
dfbb2.head()
del[dfbb2['index']]

In [411]:
dfbb2.shape,dfb.shape

((48, 6), (48, 24))

In [465]:
dfb.cell.unique()

array(['10A', '231'], dtype=object)

In [284]:
#dfb.head(),dfbb2.head()

In [530]:
for i in range(48):
    print dfb.well[i],dfbb2.well[i]

A A
A A
A A
A A
B B
B B
B B
B B
C C
C C
C C
C C
D D
D D
D D
D D
E E
E E
E E
E E
F F
F F
F F
F F
G G
G G
G G
G G
H H
H H
H H
H H
I I
I I
I I
I I
J J
J J
J J
J J
K K
K K
K K
K K
L L
L L
L L
L L


In [533]:
#dfb['mean']=dfbb2['mean']
dfb['conf']=dfbb2['mean']

In [531]:
dfb.to_excel('data_synced_with_conf.xls')

In [535]:
dfb['mean']=dfbb2['mean']

In [347]:
#dfb.iloc[14,5:14+5]=dfb.iloc[15,5:14+5]
#dfb.iloc[14,-3]=dfb.iloc[15,-3]
#dfb.iloc[14]

In [540]:

section=10
dfb['conf']=dfb['mean']*section
dfb['conf']=dfb['conf'].astype(int)
dfb['conf']=dfb['conf']*(100//section)

g = sns.factorplot(x="well", y="tm",
                   hue='cell',col='Day',
                   data=df,
                   kind="point")

### Fixing the missing D-230 from day 3 

In [373]:
a1=sa.spc_ascii(r'D:\JenuChacko\20180514\12well\231\231_well_D_photons.asc')
imshow(a1.arr.photons)
figure()
a2=sa.spc_ascii(r'D:\JenuChacko\20180514\12well\231\231_well_E_photons.asc')
imshow(a2.arr.photons)

In [375]:
hist(a1.arr.photons[a1.arr.photons>a1.arr.photons.mean()],100);
hist(a2.arr.photons[a2.arr.photons>a2.arr.photons.mean()],100);
yscale('log')

In [376]:
hist(a1.arr.tm[a1.arr.photons>a1.arr.photons.mean()],100);
hist(a2.arr.tm[a2.arr.photons>a2.arr.photons.mean()],100);
yscale('log')

In [380]:
dfsp_a1=a2.generate_df()
dfsp_a1['mask_size'].unique()

array([4662], dtype=int64)

In [382]:
dfsp_a1=a1.generate_df()
dfsp_a1['mask_size'].unique()

D:\JenuChacko\20180514\12well\231\231_well_D_photons.asc not enough points


array([2], dtype=int64)

## HETERO -MB231

In [392]:
f1=r'D:\JenuChacko\20180517_conf\231_hetero'
os.chdir(f1)
file_list=glob.glob('*photons.asc')
for i in file_list:
    print i

hetero_photons.asc
long__photons.asc
regular_dvign_photons.asc
spread___photons.asc
very_spread_photons.asc


In [410]:
%%time 

for ix,i in enumerate(file_list[1:]):
    
    l1=sa.spc_ascii(i)
    
    if ix==0:
        df1=l1.generate_df()
    else:
        df1=df1.append(l1.generate_df())
    print df1.shape

(210, 16)
(376, 16)
(599, 16)
(754, 16)
Wall time: 2.34 s


In [411]:
df1.shape

(754, 16)

In [413]:
df1.columns

Index([u'Intensity', u'a1', u'a1p', u'a1w', u'a2', u'a2p', u'chi', u'fid',
       u'g', u'itm', u'mask_size', u'phase', u's', u't1', u't2', u'tm'],
      dtype='object')

In [420]:
for i in df1.fid.unique():
    sns.distplot(df1.loc[df1.fid==i]['tm'],100,hist=False,label=i)


In [417]:
sns.boxplot(x='fid',y='tm',data=df1)

In [400]:
sns.distplot(l1_df.Intensity)

In [38]:
#https://stackoverflow.com/questions/43770507/seaborn-bar-plot-ordering
dicti=({'37':99943,'25':47228,'36':16933,'40':14996,'35':11791,'34':8030,'24' : 6319 ,'2'  :5055 ,'39' :4758 ,'38' :4611  })
pd_df = pd.DataFrame(list(dicti.iteritems()))
pd_df.columns =["Dim","Count"]
plt.figure(figsize=(12,8))
ax = sns.barplot(x="Dim", y= "Count",data=pd_df )
ax.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
ax.set(xlabel="Dim", ylabel='Count')
for item in ax.get_xticklabels():
    item.set_rotation(90)
for i, v in enumerate(pd_df["Count"].iteritems()):        
    ax.text(i ,v[1], "{:,}".format(v[1]), color='m', va ='bottom', 
    rotation=45)
plt.tight_layout()